www/backend/protected/controllers/BannerController.php
<?php

class BannerController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	
	
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
	
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','ajaxUnlinkedPaths','create','update', 'manageLinks', 'report', 'createLink', 'deleteLink'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	
	public function actionCreateLink( $banner, $path)
	{
		$model = new BannerPaths();
		$model->setAttributes( [
			'FK_banner' => $banner,
			'FK_path' => $path
		]);
		
		$response = new ResponseJSON(0);
		if(  $R = $model->save() )
		{
			$response->setResult( $R );
			$response->setData('html', $this->renderPartial( '_bannerpath', [
				'model' => $model->path
			], true));
		}
		
		$this->renderPartial( '//layouts/json', ['data' => $response]);
	}
	
	public function actionDeleteLink( $banner, $path)
	{
		$R = BannerPaths::model()->deleteAllByAttributes( [
				'FK_banner' => $banner,
				'FK_path' => $path
		]);
	
		$response = new ResponseJSON( ($R>0) ? 1 : 0 );
	
		$this->renderPartial( '//layouts/json', ['data' => $response]);
	}

	public function actions()
	{
		return array(
				 
				// сайты
				'index'=> [
						'class' 		=> 'application.actions.ActionIndex',
						'modelClass'	=> 'Banner',
						'view'			=> 'index',
				],
				 
				'create'=> [
						'class' 		=> 'application.actions.ActionCreate',
						'modelClass'	=> 'Banner',
						'view'			=> 'create',
				
				],
				 
				'update'=> [
						'class' 		=> 'application.actions.ActionUpdate',
						'modelClass'	=> 'Banner',
						'view'			=> 'update',
						'backUrl'		=>	$this->createUrl('index')
						
				],
				

			);
	}
	
	public function actionAjaxUnlinkedPaths($banner)
	{
		$banner = $this->loadModel($banner);
		
		if(Yii::app()->request->isAjaxRequest && $txt = Yii::app()->request->getParam('q'))
		{
			$txt = trim( $txt);
		
			$modelArray = SitePath::model()->findUnlinked( $banner->id, $txt );
			$returnVal = '';
		
			foreach($modelArray as $model)
			{
				$returnVal .= $model->path . "|" . $model->id ."\n";
			}
		
			echo $returnVal;
		}
	}
	
	public function actionView()
	{
		
		
		$sessionId = SiteSession::model()->getCurrentSession();
		$currentPath = SitePath::model()->getCurrentPath( Yii::app()->request );
			
		$model = Banner::model()->loadForShow($currentPath);

		if( $model === null)
			throw new CHttpException(404,'Нет подходящего баннера для показа на этой странице!');
		
		Show::model()->logShowing( $model, $sessionId, $currentPath);
		
		$this->renderPartial( '_view', [
			'model' => $model	
		]);
		
		
	}
	
	public function actionManageLinks($id)
	{
		$model = $this->loadModel($id);
	
		$filter = new SitePath('search');
		$filter->unsetAttributes();
	
		$this->render( 'manageLinks', [
				'model' => $model,
		]);
	
	
	}
	

	public function actionReport()
	{
		$report = new BannerReportForm;
		$report->setDefaults();
		
		if( $params = Yii::app()->request->getParam( 'BannerReportForm'))
		{
			$report->setAttributes( $params);
			$report->perform();
		}
		
		$this->render( '//reports/bannerReportForm/default', [
			'model' => $report	
		]);
	}
	
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Banner the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Banner::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Banner $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='banner-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

www/backend/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

www/backend/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

www/backend/protected/views/layouts/error.php
<?php /* @var $this Controller */ ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<title>Error</title>
</head>

<body>

	<?php echo $content; ?>

</body>
</html>

www/backend/protected/views/layouts/json.php
<?php  header('Content-type: text/html; charset=utf8'); 


?>
<?php
echo CJSON::encode($data);

?>

www/backend/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<?php

$themePath = Yii::app()->request->baseUrl;

Yii::app()->clientScript
    ->registerCssFile($themePath.'/assets/css/bootstrap.css')
    ->registerCssFile($themePath.'/assets/css/bootstrap-theme.css')
    ->registerCoreScript('jquery',CClientScript::POS_END)
    ->registerCoreScript('jquery.ui',CClientScript::POS_END)
    ->registerCoreScript('cookie',CClientScript::POS_END)
    ->registerScriptFile($themePath.'/assets/js/bootstrap.min.js',CClientScript::POS_END);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />



	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page" style="margin-top: 80px;">

	<div id="header">
	
	</div><!-- header -->

	<div id="mainmenu">
	<?php 
		$this->widget('bootstrap.widgets.BsNavbar', array(
			'brandLabel'	=>	false,
    		'collapse' => true,
			'htmlOptions' => array(
				'containerOptions' => 1
			),
		
			'position' => BsHtml::NAVBAR_POSITION_FIXED_TOP,
			'items'=>array(
				array(
					'class' => 'bootstrap.widgets.BsNav',
					'type' => 'navbar',
					'activateParents' => true,
					'items' => array( 
						array('label'=>'Баннеры', 'url'=>array('/banner/index'), 'visible'=>!Yii::app()->user->isGuest),
						array('label'=>'Страницы', 'url'=>array('/sitePath/index'), 'visible'=>!Yii::app()->user->isGuest),
						array('label'=>'Отчет', 'url'=>array('/banner/report'), 'visible'=>!Yii::app()->user->isGuest),
						array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			))),   
    ));
?>
		
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>